# -*- coding: utf-8 -*-
"""03_momentum_gradient.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPTAdpVThbDWku5tUJaSzbXYPyMVE2Gg
"""

import numpy as np

def momentum_gradient_descent(X, y, lr = 0.01, n_iters = 1000, momentum = 0.9):
  n_samples, n_features = X.shape
  w = np.zeros(n_features)
  v = np.zeros_like(w)
  history = []

  for _ in range(n_iters):
    pred = X.dot(w)
    error = pred - y
    grad = (2 / n_samples) * X.T.dot(error)
    v = momentum * v + lr * grad
    w -= v
    history.append(np.mean(error**2))
  return w, history