# -*- coding: utf-8 -*-
"""06_rmsprop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQJxUurtbO2ziiv91TnMLRKGLKaILIBi
"""

import numpy as np

def rmsprop(X, y, lr = 0.01, n_epochs = 100, decay = 0.9, epsilon = 1e-8):
  n_samples, n_features = X.shape
  w = np.zeros(n_features)
  E_g2 = np.zeros(n_features)
  history = []

  for epoch in range(n_epochs):
    for i in range(n_samples):
      xi = X[i]
      yi = y[i]
      pred = np.dot(xi, w)
      error = pred - yi
      grad = 2 * xi * error
      E_g2 = decay * E_g2 + (1 - decay) * grad**2
      adjusted_lr = lr / ((np.sqrt(E_g2)) + epsilon)
      w -= grad * adjusted_lr

    pred_full = X.dot(w)
    history.append(np.mean((pred_full - y)**2))

  return w, history