# -*- coding: utf-8 -*-
"""gradient_descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CU1thBro9sXeX57kNd00ffM91Zxl5HZq
"""

!pip install numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt

'''def y_function(x):
  return x**2
'''
def y_function(x):
  return np.sin(x)

'''
def y_derivative(x):
  return 2*x
'''
def y_derivative(x):
  return np.cos(x)

x = np.arange(-5, 5, 0.1)
y = y_function(x);

learning_rate = 0.01

current_pos = (3, y_function(3))

for _ in range(10):
  new_x = current_pos[0] - learning_rate * y_derivative(current_pos[0])
  new_y = y_function(x)

  plt.plot(x, y)
  plt.scatter(current_pos[0], current_pos[1], color = "red")
  plt.pause(0.001)
  plt.clf()



plt.plot(x, y)
plt.scatter(current_pos[0], current_pos[1], color = "red")
plt.pause(0.001)
plt.clf()